In [1]:
from re import M
import torch

scalar = torch.tensor(2.13)
print(scalar)
print(scalar.shape)

vector = torch.tensor([1,3,3,3,3,3,3,33,3])
print(vector)
print(vector.shape)

matrix = torch.tensor([[1,2], [2,3]])
print(matrix)



threed = torch.tensor([
    [[0,0,0],
     [0,0,0],
     [0,0,0]],
    [[0,0,0],
     [0,0,0],
     [0,0,0]],
    [[0,0,0],
     [0,0,0],
     [0,0,0]]
    ])
print(threed.shape)
print(threed)
zeros = torch.zeros(3,3,3)
print(zeros.shape)
print(zeros)

tensor(2.1300)
torch.Size([])
tensor([ 1,  3,  3,  3,  3,  3,  3, 33,  3])
torch.Size([9])
tensor([[1, 2],
        [2, 3]])
torch.Size([3, 3, 3])
tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])
torch.Size([3, 3, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


In [ ]:
import torch

x = torch.tensor([1.0, 4.0, 5.0])
w = torch.tensor([0.2, 0.5, 0.3])
b =  torch.tensor(0.4)

y = torch.dot(w,x) + b

print(y)

tensor(4.1000)
